### ISSUE TITLE
Why is the repo now 76% Jupyter notebook?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#115]
I added one .ipynb file!

From `ls -lh`:

    -rw-r--r--  1 BenjaminLee  admin   109K Jan  5 21:40 overfitting.ipynb

I know I can override it (with linguist), just wondering if something else is going on here.

**Comment by agitter** [comment]
> The percentages are calculated based on the bytes of code for each language

from the [Linguist readme](https://github.com/github/linguist) seems to be the explanation.  There is only one `ipynb` file, but it is 109 KB.  The other files recognized as code are small.

@dhimmel we could update manubot-rootstock to add a [`documentation.yml`](https://github.com/github/linguist#documentation) file for Linguist so that markdown files in the `content` subdirectory are included in the language statistics.  That's fairly low priority right now, however.

**Comment by Benjamin-Lee** [comment]
Got it, thanks.
