### ISSUE TITLE
Broken URL references

### ISSUE THREAD

**Issue by agitter** [Benjamin-Lee/deep-rules#126]
Version https://benjamin-lee.github.io/deep-rules/v/4997c72d2eae4b8d9e879310d806ee5d1078890d/ has broken URL references in `09.overfitting.md`:
```
[@url:http://dl.acm.org/citation.cfm?id=2627435.2670313] and weight decay [@url:http://dl.acm.org/citation.cfm?id=2986916.2987033]
```

![image](https://user-images.githubusercontent.com/3532898/51807036-26c55600-2247-11e9-89bf-29fc4ca41fb9.png)

I'll investigate later.

**Comment by agitter** [comment]
@dhimmel the URL citation problem here is not obvious to me.  Do you see why the id after the `=` is being truncated in the manuscript?  Citing this URL with Manubot locally works fine.

This is with Manubot v0.2.2 (specifically https://github.com/manubot/manubot/tree/dae57036de250ca1ece852a4f5b3d7f946c25d50) 

The build error: https://travis-ci.org/Benjamin-Lee/deep-rules/builds/489123811#L1912

**Comment by dhimmel** [comment]
@agitter you'll need to use tags for both these URLs. The reason is that `=` is not an allowed character in our citation string as per the [code here](https://github.com/manubot/manubot/blob/1b3ac66de9220e0b7496128a4a45e444b6d4edb1/manubot/cite/util.py#L17-L34). It's a tough situation, since we could always loosen our regex, but we risk deviating further and further from pandoc's syntax and causing other types of failures / incompatibilities.
