### ISSUE TITLE
Is this happening?

### ISSUE THREAD

**Issue by michaelmhoffman** [Benjamin-Lee/deep-rules#205]
There hasn't really been any activity since the beginning of October. @Benjamin-Lee are you still interested in taking the lead on this?

**Comment by pstew** [comment]
@agitter Would you or another PI be willing to take lead?

**Comment by rasbt** [comment]
If someone could take the lead and unify the sections we have so far, I would be onboard and happy to help with feedback and edits. Due to other project commitments and priorities at the moment, I wouldn't be able to take the lead, though.

**Comment by agitter** [comment]
My situation is the same as @rasbt.  I could help with feedback but won't be able to lead the manuscript.

**Comment by Benjamin-Lee** [comment]
Sorry everyone for being MIA: I was swamped with school and PhD applications. I'll get back to working on this tonight now that my last application is submitted.

**Comment by pstew** [comment]
> Sorry everyone for being MIA: I was swamped with school and PhD applications. I'll get back to working on this tonight now that my last application is submitted.

No worries! Happy this manuscript is not dead. Glad to hear you are applying for grad school. Good luck with applications!

**Comment by evancofer** [comment]
@Benjamin-Lee Totally understandable. Good luck with the apps!

**Comment by chevrm** [comment]
Bump. I've got some time to edit now, but don't think we're very far off. Thoughts on what needs to happen to submit?

**Comment by rasbt** [comment]
I think were we left off was tying everything together such that it looks less like a patchwork. I.e., it would take someone to make it sound less like a patchwork of pieces we added here and there. 

There also seem to be a lot of open issues, but I haven't looked through them; not sure how  many are already addressed and how many should be addressed.

**Comment by cgreene** [comment]
@Benjamin-Lee - how are things looking for you now?

**Comment by Benjamin-Lee** [comment]
@cgreene and others I’m so sorry for being slow to respond. That’s 100% my fault for losing track of this project among lots of distractions these last few months. A few notes on my part:

- I’m now back home after finishing my undergraduate degree and have settled my grad school and work plans. So, I have a lot more bandwidth to devote to this paper. 
- I’ve reread the paper as it is now with fresh eyes and am actually pretty happy with the state it’s in. 
- A few people I know have read the paper without knowing it was a draft and have expressed that, except for the TODOs left in the manuscript, it seems publishable as is. 

Therefore, I propose the following steps:

- [ ] Finish and remove all TODOs
- [ ] Add references to any new (last few months) papers with relevant information
- [ ] Attain permission from the authors who otherwise have met our criteria for inclusion
- [ ] Submit

I think getting this project in front of reviewers as soon as we can will enable us to productively resolve whatever issues they raise and get this project done as soon as we can. 

Thank you again to everyone has contributed so much effort and thought to this project — it’s been a privilege to work with you. Now let’s get this submitted.

**Comment by rasbt** [comment]
>  finishing my undergraduate degree

Congrats! :)

> A few people I know have read the paper without knowing it was a draft and have expressed that, except for the TODOs left in the manuscript, it seems publishable as is

Oh that's nice to hear!

> I think getting this project in front of reviewers as soon as we can will enable us to productively resolve whatever issues they raise and get this project done as soon as we can.

Agreed. Submitting it & getting feedback doesn't hurt. Worst case: If reviews are negative, well, we tried.

>  Add references to any new (last few months) papers with relevant information

Sounds great. I am happy to go over the paper once more after this step. I have some time next week.

**Comment by Benjamin-Lee** [comment]
Ok issues relevant to finishing the TODOs have been submitted: #208, #209, #210, #211. 

Once these issues are closed and the manuscript is in a submittable form, I will reach out to all of the potential authors to ask them to PR final approval and accountability to our contributors.md file. After a given period (TBD), we'll take those who contributed but didn't meet the authorship criteria and thank them in the acknowledgments section. Then we submit!

**Comment by Benjamin-Lee** [comment]
I'm going to close this issue the answer to its question is **yes**.
