### ISSUE TITLE
Consider re-phrasing "biology" to "life sciences" for precision

### ISSUE THREAD

**Issue by juancarmona** [Benjamin-Lee/deep-rules#301]
Throughout the paper, we make reference to "biology" when in fact we're really commenting on a breadth of research spanning basic science (which is "biology") to clinical science and translational studies (which are biomedical). Importantly, the "life sciences" category fits all of these types of science in a more precise manner than "biology" alone. For instance, let's please consider this section in Tip 1: 
>As long as large amounts of accurate and labeled data are available, applications to areas of biology with related data characteristics, such as genetic medicine [28], radiology [29], microscopy [30], and pharmacovigilance [31], are similarly likely to benefit from deep learning techniques.

In this excerpt above, using "...applications to areas of life sciences research with related data characteristics..." makes much more sense--as neither radiology nor genetic medicine would be considered sub-disciplines of "biology"

**Comment by rasbt** [comment]
That's a good and important point. Since we are planning to submit the article to a biology journal, I am wondering if a change could be problematic though. 

I was just looking up the definition of life sciences on Wikipedia

> Biology is the natural science that studies life and living organisms, with the other life sciences its sub-disciplines.

(Soure: https://en.wikipedia.org/wiki/List_of_life_sciences)

it seems ok to leave it as biology? I am not sure how authoritative this wiki article and definition is though.

Instead of referring to biology, would "biological sciences" cover it? Or "biological and biomedical sciences"?

**Comment by juancarmona** [comment]
I think that "biological and biomedical sciences" could work well. I think that "biology" is more widely appreciated as basic science--i.e., understood to mean more about model organisms like mice, frogs, plants, fungi, etc.--whereas biomedical/public health science/translational efforts are more about people, electronic health records, etc. Open to ideas

**Comment by cgreene** [comment]
I like life sciences but don't have strong enough feelings to argue heavily in its favor :)

**Comment by rasbt** [comment]
Initially, I was a bit too worried about too many changes from biology -> life sciences (given that as per title of the paper, we have a biology focus). Looking through all the 10 tips, I think it's really just tip 1 where we have such a case where rephrasing biology makes sense.

The only other sentence I could find was in Tip 7:

> When working with biological and medical data, one must also carefully consider potential sources of bias and/or non-independence when defining training and test sets.

I am actually very surprised how rarely we use "biology/biological" in later chapters :).

I am convinced that changing it to

> "...applications to areas of life sciences research with related data characteristics..." 

is actually nicer because these applications are really different from the other biology research we usually refer to when we use the term biology.

**Comment by juancarmona** [comment]
@rasbt, I completely agree with these points and edits

**Comment by rasbt** [comment]
Sounds good  :). I went ahead and submitted a PR to check this of the list :)
