### ISSUE TITLE
Update Manubot thumbnail

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#312]
Since we've updated the last tip, we should ideally update the thumbnail. This is low priority and it's fine if it doesn't get done at all since the one in the manuscript is up to date as of #309 and #310.

**Comment by rasbt** [comment]
Do you mean the thumbnail at

[https://github.com/Benjamin-Lee/deep-rules/blob/master/thumbnail.png](https://github.com/Benjamin-Lee/deep-rules/blob/master/thumbnail.png) ?

I am wondering how it's supposed to be different from

[https://github.com/Benjamin-Lee/deep-rules/blob/master/content/images/thumbnail_tips_overview.png](https://github.com/Benjamin-Lee/deep-rules/blob/master/content/images/thumbnail_tips_overview.png)

Is this something that could be solved by copy-and-pasting the latter to the former location?

**Comment by Benjamin-Lee** [comment]
I think it's the thumbnail used for various purposes such as the Manubot collection. I'm frankly not 100% sure so maybe @dhimmel or @agitter can chime in

**Comment by dhimmel** [comment]
The thumbnail is used for https://manubot.org/catalog/ (the deep-rules image there will update within a week). It's also used for previewing on social media. For example, if you enter https://benjamin-lee.github.io/deep-rules/v/3a5ef62e124281949d9097d5dde39a58a21a4ff4/ at https://cards-dev.twitter.com/validator:

> ![image](https://user-images.githubusercontent.com/1117703/104532358-07fc2d80-55de-11eb-9cf6-b6e1f87d0dc6.png)

**Comment by rasbt** [comment]
Thanks for clarifying! :)

(I addition to that, I was mainly wondering why we have the thumbnail in two places / whether the one needs to have specific dimensions whereas the other doesn't)

**Comment by agitter** [comment]
We have https://github.com/Benjamin-Lee/deep-rules/blob/master/content/images/thumbnail_tips_overview.png because it needs to be in a subdirectory of the content directory if we want to use it in the manuscript as Figure 1.

I think we can delete https://github.com/Benjamin-Lee/deep-rules/blob/master/thumbnail.png so that we don't have to maintain two copies of the same image.  These are the exact same file, right?  We can explicitly tell Manubot where the thumbnail is for the catalog.  I'll try this in #313.
