### ISSUE TITLE
Logo Feedback

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#47]
In an effort to help with publicity, I hired a logo designer on Fiverr for the project. They just came back with their first draft of the logo:

![deeprules-02](https://user-images.githubusercontent.com/13618205/48681283-83353680-eb6f-11e8-8ed6-1406e4b803b5.jpg)

We have 24 hours to request revisions, so any ideas/comments/critiques to communicate to the designer would be highly appreciated.

**Comment by rasbt** [comment]
Looks nice. The only thing is that this currently looks somehow like it would be for DNA-related analyses. I think this is fine for people who are e.g., not biologists though. This brings up the question: who would be the intended audience for this? 

If the audience would be biologists who may want to use deep learning in their projects, shouldn't the logo focus more on something that captures ML/AI/DL? (or maybe I am misinterpreting the logo  :))

Overall though, I think the logo is not too bad. If we stick with this, I think we may want to somehow make the "deep learning in biology" part more obvious. Maybe putting line break before
"Deep Learning in Biology" and then increasing the font size. I am not a designer though :P

**Comment by jmschrei** [comment]
I like it in general, but is it possible to replace the node+edge structure inside the double helix with dense neural networks, potentially going from left to right?

I'm not entirely sure what the purpose of further publicizing the manuscript is. Naturally, input from more people is helpful and no one should be discouraged from participating. However, I would propose that at this point we should focus on condensing the rule list down to 10 and writing a draft of the manuscript. It's easier, and I think more useful to the community, to publicize work after it's been created.

**Comment by Benjamin-Lee** [comment]
@jmschrei Agree wholeheartedly with switching to dense neural network–I don't know if that came through to the designer.

With respect to further publicity, I also agree that we should start condensing the rules down. Projects with logos always seem more "official" to me, so for the $25, I thought I'd splurge. H/T to [rasbt/MLxtend](http://github.com/rasbt/mlxtend) for inspiring the logo.

**Comment by rasbt** [comment]
@jmschrei. Good point. I was under the impression it's a logo for the abstract (like JCIM has/requires) but I see the other 10 rules articles at PLoS Bio doesn't have logos. 

Generally, I agree with you that publicizing would be more appropriate after the manuscript is finished and accepted for publication, otherwise it would be a bit awkward :). We can use it then though to share it because I guess we won't have any other figures in the manuscript? (not sure what the actual guidelines/requirements for the 10 rules articles are though)

Based on the issue tracker, I think we already have a whole bunch of rules that are good, and I would say we may already have captured all the important things to think about. A next step would maybe be that we vote on the rules to include. Maybe everyone (the contributors here) should give a 1-10 score for each rule and then we can take the top 10 rules based on the highest average scores and see if the results make sense (and whether we maybe need to look for additional ideas). 

> H/T to rasbt/MLxtend for inspiring the logo.

Oh wow small world :)

**Comment by evancofer** [comment]
I realize this is a little late, but it looks pretty sharp!

**Comment by AlexanderTitus** [comment]
I agree with the updates, and looks great to me!
