### ISSUE TITLE
Should we add the issues listed for each rule to its corresponding project?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#84]
For example, in [`rules.md`](rules.md), #7 is listed as being part of the `Concepts that apply to machine learning also apply to deep learning` rule. Should we add it to the project for the rule and mark it as closed when the issue's topic has been addressed in the manuscript?

**Comment by rasbt** [comment]
Hm, closing the issue sounds good to keep things organized in terms of handling the issue tracker as a "to do" list.

Additionally, it would maybe be good to modify the title of the issue so that we can later more easily search for the issues that were included in case we need to reopen it for further discussion. 

E.g., we could rename "Normalize, normalize, normalize." (title of rule #7) to "[Included] Normalize, normalize, normalize."

Alternatively, we could also use the "Labels" feature for that and tag rules with a label "included" or "in manuscript"

**Comment by Benjamin-Lee** [comment]
I'm a fan of using the Labels feature since it makes searching and visual grepping of the issues list that much easier. Will get on implementing it as soon as I have a chance

**Comment by evancofer** [comment]
Labels sounds like a good idea.

**Comment by Benjamin-Lee** [comment]
Ok I'm on this

**Comment by Benjamin-Lee** [comment]
Done
